os:
  edit: 'nvim --server "$NVIM" --remote-tab "{{filename}}"'
  editAtLine: 'nvim --server "$NVIM" --remote-tab "{{filename}}"'
  editAtLineAndWait: 'nvim --server "$NVIM" --remote-tab-wait "{{filename}}"'
  openDirInEditor: 'nvim --server "$NVIM" --remote-tab "{{dir}}"'
git:
  autoFetch: false
